### ISSUE TITLE
How about something like Final by Default

### ISSUE THREAD

**Issue by bangarharshit** [JakeWharton/nopen#6]
Probably a check which checks if the class is not marked with `@Open` or abstract should not have any subclasses. 

On a related note, it will be a great thing to have FinalByDefault (similar to NonNullByDefault) baked in the type system via EP check or checker framework.

**Comment by JakeWharton** [comment]
If it's not `@Open` or `abstract` though then what is it? Isn't `final` all that's left?

**Comment by bangarharshit** [comment]
Fair point. Just avoiding the keyword final. It should be declared `@Open` or `abstract`. In the current check `Non-final, Non-abstract classes without the @Open annotation will be marked with an error.`. How about just treating them as `final`. All things are `final` by default and you have to mark `@Open` to make it subclassable.

**Comment by JakeWharton** [comment]
That still allows their subclassing by downstream libraries. I suppose if the type isn't effectively public then perhaps the check shouldn't apply?

**Comment by bangarharshit** [comment]
Oh. Didn't think of this use case.
